#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "prowlarr"
name = "Prowlarr"
description.en = "Complete management of your indexers for Radarr, Sonarr, Lidarr..."
description.fr = "Gestion complète de vos indexeurs pour Radarr, Sonarr, Lidarr..."

version = "2.3.5.5327~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://prowlarr.com"
admindoc = "https://wiki.servarr.com/prowlarr"
code = "https://github.com/Prowlarr/Prowlarr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prowlarr"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.3.5.5327/Prowlarr.master.2.3.5.5327.linux-core-x64.tar.gz"
    amd64.sha256 = "70c2a200f90b5e60239b0ca0cba2ed879ce31f3be68cf1bfe676e6b30292a9d0"

    arm64.url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.3.5.5327/Prowlarr.master.2.3.5.5327.linux-core-arm64.tar.gz"
    arm64.sha256 = "f6979b8cf172d2c918dc2a520b82e0eed09dabcde02e8a4f961c23da26181443"
    armhf.url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.3.5.5327/Prowlarr.master.2.3.5.5327.linux-core-arm.tar.gz"
    armhf.sha256 = "671044fbf7db22d23d48b6bc61c1ec8aab16994ab4a2cba7805a4248a6601eaf"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^Prowlarr\\.master\\..*\\.linux-core-x64\\.tar\\.gz$"
    autoupdate.asset.arm64 = "^Prowlarr\\.master\\..*\\.linux-core-arm64\\.tar\\.gz$"
    autoupdate.asset.armhf = "^Prowlarr\\.master\\..*\\.linux-core-arm\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl, mediainfo, sqlite3"
