#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "prowlarr"
name = "Prowlarr"
description.en = "Complete management of your indexers for Radarr, Sonarr, Lidarr..."
description.fr = "Gestion complète de vos indexeurs pour Radarr, Sonarr, Lidarr..."

version = "2.4.0.5397~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://prowlarr.com"
admindoc = "https://wiki.servarr.com/prowlarr"
code = "https://github.com/Prowlarr/Prowlarr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prowlarr"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.4.0.5397/Prowlarr.master.2.4.0.5397.linux-core-x64.tar.gz"
    amd64.sha256 = "95c1285d286513fe9565767291bde93940fdb432dbad3fdd41faa60f73eabcca"

    arm64.url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.4.0.5397/Prowlarr.master.2.4.0.5397.linux-core-arm64.tar.gz"
    arm64.sha256 = "3e54bec60bef729a50a92d5dbee3c7dfa0b067074de4f145d25cfdc6a102314f"
    armhf.url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.4.0.5397/Prowlarr.master.2.4.0.5397.linux-core-arm.tar.gz"
    armhf.sha256 = "a91062e806fe0aa3f25f52a3277a527a145abb402b9a6640b2fc613232f39857"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^Prowlarr\\.master\\..*\\.linux-core-x64\\.tar\\.gz$"
    autoupdate.asset.arm64 = "^Prowlarr\\.master\\..*\\.linux-core-arm64\\.tar\\.gz$"
    autoupdate.asset.armhf = "^Prowlarr\\.master\\..*\\.linux-core-arm\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl, mediainfo, sqlite3"
